Splitting off into separate kmeans file (TODO: RESOLVE SYNC ISSUE)
Tweaked plans a bit, going to try to first just isolate off everything Street or Metric related over in layer.rs, with kmeans.rs now only being defined in terms of Histograms, Energy, usize, and f32s. Which should hopefully be enough to start writing decent unit tests (since we're not locked into the 4 specific values over in stree.rs for our 'k' and 't' values). Leaving a lot of stuff using 'self' for now though.

Note: won't actually run yet, still need to resolve this one last issue:

```
   Compiling robopoker v0.1.1 (/Users/claymation/Documents/GitHub/robopoker)
error[E0277]: `Self` cannot be shared between threads safely
   --> src/clustering/kmeans.rs:187:18
    |
187 |             .map(|h| (h, self.nearest_neighbor(centers_start, h)))
    |              --- ---^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |              |   |
    |              |   `Self` cannot be shared between threads safely
    |              |   within this `{closure@src/clustering/kmeans.rs:187:18: 187:21}`
    |              required by a bound introduced by this call
    |
    = note: required because it appears within the type `&Self`
note: required because it's used within this closure
   --> src/clustering/kmeans.rs:187:18
    |
187 |             .map(|h| (h, self.nearest_neighbor(centers_start, h)))
    |                  ^^^
note: required by a bound in `rayon::iter::ParallelIterator::map`
   --> /Users/claymation/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/rayon-1.10.0/src/iter/mod.rs:603:34
    |
601 |     fn map<F, R>(self, map_op: F) -> Map<Self, F>
    |        --- required by a bound in this associated function
602 |     where
603 |         F: Fn(Self::Item) -> R + Sync + Send,
    |                                  ^^^^ required by this bound in `ParallelIterator::map`
help: consider further restricting `Self`
    |
177 |     fn compute_next_kmeans(&self, centers_start: &Vec<Histogram>) -> Vec<Histogram> where Self: Sync /* K */ {
    |                                                                                     ++++++++++++++++

error[E0609]: no field `kmeans` on type `&Self`
   --> src/clustering/kmeans.rs:573:24
    |
39  | pub trait Clusterable {
    | --------------------- type parameter 'Self' declared here
...
573 |             .zip(&self.kmeans)
    |                        ^^^^^^ unknown field

error[E0277]: `Self` cannot be shared between threads safely
   --> src/clustering/kmeans.rs:646:18
    |
646 |             .map(|(center1, center2)| self.distance(center1, center2)) // 1-D vector with length k^2
    |              --- --------------------^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |              |   |
    |              |   `Self` cannot be shared between threads safely
    |              |   within this `{closure@src/clustering/kmeans.rs:646:18: 646:38}`
    |              required by a bound introduced by this call
    |
    = note: required because it appears within the type `&Self`
note: required because it's used within this closure
   --> src/clustering/kmeans.rs:646:18
    |
646 |             .map(|(center1, center2)| self.distance(center1, center2)) // 1-D vector with length k^2
    |                  ^^^^^^^^^^^^^^^^^^^^
note: required by a bound in `rayon::iter::ParallelIterator::map`
   --> /Users/claymation/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/rayon-1.10.0/src/iter/mod.rs:603:34
    |
601 |     fn map<F, R>(self, map_op: F) -> Map<Self, F>
    |        --- required by a bound in this associated function
602 |     where
603 |         F: Fn(Self::Item) -> R + Sync + Send,
    |                                  ^^^^ required by this bound in `ParallelIterator::map`
help: consider further restricting `Self`
    |

```