Change back to 2 clusters that should always get something assinged
As discussed in the comment thread the error issues, there's no natural identity we can use there. So if the cluster doesn't have anything assigned, not much we can do.
Good news is that I can now see that there's not actually a need to have the starting stuff close together - even starting with 0.1 and 0.8 we're getting nice clustering results like:

elkan: 1.1891768, original: 1.1891768
elkan: 0.46755302, original: 0.41243306

or

elkan: 1.1891769, original: 1.1891768
elkan: 0.41243306, original: 0.41247895
elkan: 0.34328577, original: 0.33933988

or passing sometimes.

... annoyingly still also do get
```

thread '<unnamed>' panicked at src/clustering/kmeans.rs:817:63:
called `Option::unwrap()` on a `None` value
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

thread '<unnamed>' panicked at src/clustering/kmeans.rs:817:63:
called `Option::unwrap()` on a `None` value

thread '<unnamed>' panicked at src/clustering/kmeans.rs:817:63:
called `Option::unwrap()` on a `None` value

thread '<unnamed>' panicked at src/clustering/kmeans.rs:817:63:
called `Option::unwrap()` on a `None` value

thread '<unnamed>' panicked at src/clustering/kmeans.rs:817:63:
called `Option::unwrap()` on a `None` value

thread '<unnamed>' panicked at src/clustering/kmeans.rs:817:63:
called `Option::unwrap()` on a `None` value

thread '<unnamed>' panicked at src/clustering/kmeans.rs:817:63:
called `Option::unwrap()` on a `None` value

thread '<unnamed>' panicked at src/clustering/kmeans.rs:817:63:
called `Option::unwrap()` on a `None` value

thread '<unnamed>' panicked at src/clustering/kmeans.rs:817:63:
called `Option::unwrap()` on a `None` value

thread '<unnamed>' panicked at src/clustering/kmeans.rs:817:63:
called `Option::unwrap()` on a `None` value

thread '<unnamed>' panicked at src/clustering/kmeans.rs:817:63:
called `Option::unwrap()` on a `None` value

failures:
    clustering::kmeans::tests::test_kmeans_elkan_original_match
```

but aside from that, only remaining issue is, WHY are these different here / constantly changing? (It *should* be something related to the test given that the 'real' runs I did were actually matching at each step... Also is odd that the test is actually sporadically passing; if this was entirely random I would expect that to be basically impossible.)