Further increase # points to lower chances of flake
Randomly hit same

thread 'clustering::kmeans::tests::test_kmeans_elkan_rms_decreases' panicked at src/clustering/kmeans.rs:593:13:
not yet implemented: Figure out what to do here for the center - no points assigned to it currently!!
stack backtrace:
   0: __rustc::rust_begin_unwind
             at /rustc/17067e9ac6d7ecb70e50f92c1944e545188d2359/library/std/src/panicking.rs:697:5
   1: core::panicking::panic_fmt
             at /rustc/17067e9ac6d7ecb70e50f92c1944e545188d2359/library/core/src/panicking.rs:75:14
   2: robopoker::clustering::kmeans::compute_next_kmeans_tri_ineq
             at ./src/clustering/kmeans.rs:593:13
   3: robopoker::clustering::kmeans::cluster
             at ./src/clustering/kmeans.rs:188:30
   4: robopoker::clustering::kmeans::tests::test_kmeans_elkan_rms_decreases
             at ./src/clustering/kmeans.rs:927:33
   5: robopoker::clustering::kmeans::tests::test_kmeans_elkan_rms_decreases::{{closure}}
             at ./src/clustering/kmeans.rs:910:41
   6: core::ops::function::FnOnce::call_once
             at /rustc/17067e9ac6d7ecb70e50f92c1944e545188d2359/library/core/src/ops/function.rs:250:5
   7: core::ops::function::FnOnce::call_once
             at /rustc/17067e9ac6d7ecb70e50f92c1944e545188d2359/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

here (probably cause the # histograms is a bit higher in these two tests, ie 5) after a LONG stretch of not hitting it.

It's already pretty rare, but since it doesn't really hurt performance to bump up the # points, and that tends to help avoid this, we might as well increase it a bit for them.